SUPPORTED_LANGUAGES = {
    'en_GB': 'English (GB)',
    'bg_BG': 'Bulgarian',
    'ca_ES': 'Catalan',
    'zh_CN': 'Chinese Simplified',
    'zh_TW': 'Chinese Traditional',
    'cs_CZ': 'Czech',
    'da_DK': 'Danish',
    'de_DE': 'German',
    'el_GR': 'Greek',
    'en_US': 'English (US)',
    'es_ES': 'Spanish',
    'et_EE': 'Estonian',
    'fi_FI': 'Finnish',
    'fr_FR': 'French',
    'hr_HR': 'Croatian',
    'hu_HU': 'Hungarian',
    'is_IS': 'Icelandic',
    'it_IT': 'Italian',
    'lt_LT': 'Lithuanian',
    'lv_LV': 'Latvian',
    'nl_NL': 'Dutch',
    'no_NO': 'Norwegian',
    'pl_PL': 'Polish',
    'pt_BR': 'Portuguese (Brazil)',
    'pt_PT': 'Portuguese (Portugal)',
    'ro_RO': 'Romanian',
    'ru_RU': 'Russian',
    'sk_SK': 'Slovak',
    'sl_SI': 'Slovenian',
    'sv_SE': 'Swedish',
    'tr_TR': 'Turkish',
    'ja_JP': 'Japanese',
    'es_PE': 'Spanish (Peru)',
    'id_ID': 'Indonesian',
    'ms_MY': 'Malay',
    'th_TH': 'Thai',
    'vi_VN': 'Vietnamese',
    'ko_KR': 'Korean'
}

# Source language code (assuming English GB is the source)
SOURCE_LANGUAGE = 'en_GB' 